#!/usr/bin/env python3

import argparse
import csv
import datetime
import sys

from pathlib import Path

source_path = None

if __name__ == "__main__":
    parser = argparse.ArgumentParser(sys.argv[0],
                                     description="Create a field definition file for a directory of csv files.")

    parser.add_argument("-p", "--path",
                        dest="source_path",
                        help="The directory containing the csv files",
                        required=True)

    args = parser.parse_args()

    source_path = Path(args.source_path)
    if not source_path.exists():
        raise NotADirectoryError(f"{source_path} not found or is not a directory")
        exit(-1)

    print(f"# Generated {datetime.datetime.now()}", end="\n\n")
    for f in source_path.glob("*.csv"):
        filename = Path(f)
        with open(filename, "r") as csv_file:
            csv_data = csv.DictReader(csv_file)
            print(f"[{filename.stem}]")
            found_id = False
            for field_name in csv_data.fieldnames:
                field_name = field_name.replace(" ", "_")
                field_type = "TEXT"
                if "_id" in field_name and found_id is True:
                    field_type = "INTEGER"
                if ("_id" in field_name or "id" == field_name) and found_id is not True:
                    field_type = "INTEGER PRIMARY KEY AUTONUMBER"
                    found_id = True
                print(f"{field_name} = {field_type}")
            print()
